services:
  redis:
    image: "redis:latest"
    container_name: task2_redis
    ports:
      - "6379:6379"

  db:
    container_name: task2_db
    image: postgres:15.3
    restart: always
    volumes:
      - task2_db:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    container_name: task2_backend
    build: .
    command: sh -c "./start.sh"
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on: 
      - db
      - redis

  celery-worker:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - web
    links:
      - web
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - web
    links:
      - web
    env_file:
      - .env

volumes:
  task2_db:
    name: task2_db