# Generated by Django 4.2.5 on 2023-10-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=20)),
                ("carrier", models.CharField(max_length=50)),
                ("sender_address", models.TextField()),
                ("receiver_address", models.TextField()),
                ("article_name", models.CharField(max_length=50)),
                ("article_quantity", models.IntegerField()),
                ("article_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sku", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
